server:
  port: 9000
spring:
  application:
    name: gulimall-order
  datasource:
    username: root
    password: root3306
    url: jdbc:mysql://152.136.103.162:3306/gulimall_sms
    driver-class-name: com.mysql.cj.jdbc.Driver
mybatis-plus:
  global-config:
    db-config:
      id-type: auto
  mapper-locations: classpath:/mapper/**/*.xml